FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy semua file dari host ke container
COPY . .

# Expose port
EXPOSE 3005

# Jalankan aplikasi
CMD ["npm", "start"]